# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: GiulioSorrentino.CBriscola.Avalonia
PackageVersion: 0.7.7
InstallerType: wix
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.8
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/numerunix/CBriscola.Avalonia/releases/download/0.7.7/CBriscola.Avalonia-0.7.7-2-x64.msi
  InstallerSha256: 934C995635572A412997595DCD5BE1A819A169F872A9E857109A3AC45F699687
- Architecture: arm64
  InstallerUrl: https://github.com/numerunix/CBriscola.Avalonia/releases/download/0.7.7/CBriscola.Avalonia-0.7.7-2-arm64.msi
  InstallerSha256: B26D261A6BCC08982E8933073AC0BBD478BE69D8C33033DAB48F51F01A2A61FD
ManifestType: installer
ManifestVersion: 1.6.0
