# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: GiulioSorrentino.numeronesfortuneinavalonia
PackageVersion: 3.0.0.5
InstallerType: wix
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.9
ProductCode: '{90D24925-7418-48AD-9950-676C5F839B26}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/GiulianoSpaghetti/numfortune.material/releases/download/3.0/numfortune.Avalonia-3.0.0.5-material-amd64.msi
  InstallerSha256: 28D96E2E5B4CED1A5893FFF0E67D9F72EAA8B1796C24D626127E3886B8CBB707
- Architecture: arm64
  InstallerUrl: https://github.com/GiulianoSpaghetti/numfortune.material/releases/download/3.0/numfortune.Avalonia-3.0.0.5-material-arm64.msi
  InstallerSha256: FD5B4D9050AEFCBD29D3090E8008B1BF387EC16FF28B6D0E32CA274DAC889C28
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2025-01-27
