# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: GiulioSorrentino.CBriscola.Avalonia
PackageVersion: "1.0"
InstallerType: wix
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.9
ProductCode: '{68B61DE0-07A0-499E-B3FB-F15883741EB4}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/GiulianoSpaghetti/CBriscola.Material/releases/download/1.0/CBriscola.Avalonia-1.0-material-amd64.msi
  InstallerSha256: 62AD8496F5876B71DC6DC00297A3A167CD4CC0F4226A1B7D7CED419938D482B1
- Architecture: arm64
  InstallerUrl: https://github.com/GiulianoSpaghetti/CBriscola.Material/releases/download/1.0/CBriscola.Avalonia-1.0-material-arm64.msi
  InstallerSha256: C20EAF07079B1FCEBEBADCFEDC0BD8F1896C982425A7FE0FF1BFC31AC7FD5957
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2025-04-08
