# Created using wingetcreate 1.9.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: GiulioSorrentino.numeronesoft-pixel9fold
PackageVersion: "0.1"
InstallerType: exe
InstallerSwitches:
  Silent: -o"C:\windows\web\wallpaper" -y
  SilentWithProgress: -o"C:\windows\web\wallpaper" -y
Installers:
- Architecture: x64
  InstallerUrl: http://numeronesoft.ddns.net:8080/numeronesoft-pixel9fold.exe
  InstallerSha256: F41A97F1C3181A6174156CEECAFB29F05AA28BC4C0B28BC81C13E61233FB2CE3
ManifestType: installer
ManifestVersion: 1.9.0
