# Created using wingetcreate 1.6.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: GiulioSorrentino.CBriscola.WPF
PackageVersion: 0.7.1
InstallerType: wix
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.8
ProductCode: '{DD0F1B46-75C9-4672-AFD4-398586A546E7}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/GiulianoSpaghetti/CBriscola.WPF/releases/download/0.7.1/CBriscolaWPF-0.7.1-amd64.msi
  InstallerSha256: CB347ED40BEB591EF2033ADE4277380A8A0BA663A77F994001414A7DEF8C2A13
- Architecture: arm64
  InstallerUrl: https://github.com/GiulianoSpaghetti/CBriscola.WPF/releases/download/0.7.1/CBriscolaWPF-0.7.1-arm64.msi
  InstallerSha256: 9E968DCF0D43F2204DACE8DBB5397C271866B0A4BB414CABBC811BA40E5EBABE
ManifestType: installer
ManifestVersion: 1.6.0
ReleaseDate: 2024-10-25
