# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: GiulioSorrentino.wxBriscola
PackageVersion: 0.6.3
InstallerType: wix
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/numerunix/wxBriscola-for-Windows/releases/download/0.6.3/wxBriscola-0.6.3-x64.msi
  InstallerSha256: 2850C475CB4C357A055D71EC6AF3EA368ECE59DACF1AE0DDA4FE147A831BB35D
ManifestType: installer
ManifestVersion: 1.6.0
